[package]
name = "raylib_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = { version = "3.7" }
chrono = "0.4.23"
soloud = "1.0.2"
rodio = "0.17.1"
